NeferNedjer/MediaSmart-ECF3-

- view/login.php
login html formulaire de connexion
> loginhtml formulaire de connexion

- controller/ControllerMedia.php
- controller/ControllerUser.php
- entity/Media.php
- entity/User.php
- model/ModelMedia.php
- model/ModelUser.php
- view/homepage.php
- view/login.php
- view/signup.php
> add homepage

- controller/ControllerMedia.php
- index.php
- view/404.php
> add 404.php

- assets/js/newmedia.js
- assets/scss/style.scss
- controller/ControllerMedia.php
- entity/Media.php
- index.php
- model/ModelMedia.php
- view/newmedia.php
Début formulaire Média de création HTML et JS
> Début formulaire Média de création HTML et JS

- controller/ControllerEmployee.php
- index.php
- model/ModelEmployee.php
- view/loginEmployee.php
> add login employee

- controller/ControllerEmployee.php
- controller/ControllerUser.php
- index.php
- view/login.php
- view/loginEmployee.php
- view/signup.php
- view/verify-token.php
> change host

- controller/ControllerEmployee.php
- index.php
- model/ModelEmployee.php
- view/createEmployee.php
- view/dashboardEmployee.php
- view/getUser.php
> create dashboard employee

- assets/scss/style.scss
- view/createEmployee.php
modification de form en html et css
>  modifications form en html et css

- controller/ControllerUser.php
- view/modifUser.php
Formulaire de modification user
> Formulaire de modification user

- model/ModelEmployee.php
> new sql requete

- model/ModelEmployee.php
> new sql requete with 0

- entity/User.php
- view/dashboardEmployee.php
add right part of dashboard employee
> add right part of dashboard employee

- controller/ControllerEmployee.php
- view/dashboardEmployee.php
correction of right dashboard employee
> correction of right dashboard employee

- assets/js/employee.js
- view/getUser.php
correction du bouton retour de getuser
> correction du bouton retour de getuser

- controller/ControllerUser.php
- model/ModelEmployee.php
- model/ModelEmprunt.php
- model/ModelUser.php
- view/login.php
LOGIN USER EMPLOYEE + GESTION DES ERREURS
> LOGIN USER EMPLOYEE + GESTION DES ERREURS

- controller/ControllerEmployee.php
- index.php
- model/ModelExemplaire.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
- vendor/composer/installed.php
- view/dashboardMedia.php
> create dashboard media

- assets/js/ajaxMedia.js
- controller/ControllerMedia.php
- model/ModelAuthor.php
- model/ModelMedia.php
- view/dashboardMedia.php
> ajax searchbarre media

- model/ModelUser.php
> last connexion

- assets/scss/style.scss
- controller/ControllerUser.php
- view/dashboardEmployee.php
correction de conflit en html et récup des datas du formulaire
> correction de conflit en html et récup des datas du formulaire

- controller/ControllerEmployee.php
- controller/ControllerUser.php
- entity/Media.php
- index.php
- model/ModelEmprunt.php
- model/ModelExemplaire.php
- view/dashboardEmployee.php
- view/dashboardMedia.php
> dashboard Media

- view/dashboardEmployee.php
- view/dashboardMedia.php
- view/homepage.php
> add some route

- controller/ControllerMedia.php
- index.php
- model/ModelMedia.php
- view/dashboardEmployee.php
- view/homepage.php
creation de la barre de recherhce des medias sur la homepage
> creation de la barre de recherhce des medias sur la homepage

- model/ModelMedia.php
- view/dashboardEmployee.php
correction de problemes suite au merge
> correction de problemes suite au merge

- controller/ControllerMedia.php
- index.php
- model/ModelMedia.php
- view/dashboardEmployee.php
- view/dashboardMedia.php
- view/modifMedia.php
ajout de la modification du maedia
> ajout de la modification du maedia

- controller/ControllerEmployee.php
- index.php
- model/ModelEmployee.php
- view/dashboardEmployee.php
- view/getEmployee.php
creation de la page gestion des employes
> creation de la page gestion des employes

- view/dashboardMedia.php
oubli d'un lien donc rajout du lien liste des employés
> oubli d'un lien donc rajout du lien liste des employés

- controller/ControllerUser.php
- index.php
- view/compteUser.php
- view/dashboardUser.php
- view/homepage.php
- view/signup.php
rajout des liens media sur le titre des livres
> rajout des liens media sur le titre des livres

- view/detailMedia.php
ajout du bouton reservation au detail media
> ajout du bouton reservation au detail media

- assets/js/ajaxMedia2.js
- view/dashboardEmployee.php
- view/dashboardHistoric.php
- view/dashboardMedia.php
- view/getEmployee.php
- view/homepage.php
ajout de differents liens sur la homepage et la navbar
> ajout de differents liens sur la homepage et la navbar

- view/detailMedia.php
bouton resa en fonction de la connexion et de la dispo
> bouton resa en fonction de la connexion et de la dispo

- view/detailMedia.php
ajpout condition de reservation
> ajpout condition de reservation

- view/detailMedia.php
ajout de liens sur detailmedia
> ajjout de liens sur detailmedia

- view/homepage.php
ajout des boutons en fonction de qui se connecte
> ajout des boutons en fonction de qui se connecte
